export const PICK_APPOINTMENT_DATE = "PICK_APPOINTMENT_DATE";
export const MAKE_APPOINTMENT = "MAKE_APPOINTMENT";
export const GET_APPOINTMENTS = "GET_APPOINTMENTS";
export const UPDATE_APPOINTMENT_STATUS = "UPDATE_APPOINTMENT_STATUS";
export const GET_STATUS_COUNT = "GET_STATUS_COUNT";
export const APPOINTMENT_VISITED_ACTION = "APPOINTMENT_VISITED_ACTION";
export const APPOINTMENT_ERROR = "APPOINTMENT_ERROR";

// PRESCRIPTION;
export const CREATE_PRESCRIPTION = "CREATE_PRESCRIPTION";
export const UPDATE_MEDICINE = "UPDATE_MEDICINE";
export const PRESCRIPTION_ERROR = "PRESCRIPTION_ERROR";
